/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SwiftlyIntelligenceRouteImport } from './routes/swiftly.intelligence'
import { Route as SwiftlyDeploymentRouteImport } from './routes/swiftly.deployment'
import { Route as SwiftlyCorridorsRouteImport } from './routes/swiftly.corridors'
import { Route as ApiCopilotRouteImport } from './routes/api/copilot'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SwiftlyIntelligenceRoute = SwiftlyIntelligenceRouteImport.update({
  id: '/swiftly/intelligence',
  path: '/swiftly/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const SwiftlyDeploymentRoute = SwiftlyDeploymentRouteImport.update({
  id: '/swiftly/deployment',
  path: '/swiftly/deployment',
  getParentRoute: () => rootRouteImport,
} as any)
const SwiftlyCorridorsRoute = SwiftlyCorridorsRouteImport.update({
  id: '/swiftly/corridors',
  path: '/swiftly/corridors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopilotRoute = ApiCopilotRouteImport.update({
  id: '/api/copilot',
  path: '/api/copilot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/swiftly/corridors': typeof SwiftlyCorridorsRoute
  '/swiftly/deployment': typeof SwiftlyDeploymentRoute
  '/swiftly/intelligence': typeof SwiftlyIntelligenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/swiftly/corridors': typeof SwiftlyCorridorsRoute
  '/swiftly/deployment': typeof SwiftlyDeploymentRoute
  '/swiftly/intelligence': typeof SwiftlyIntelligenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/swiftly/corridors': typeof SwiftlyCorridorsRoute
  '/swiftly/deployment': typeof SwiftlyDeploymentRoute
  '/swiftly/intelligence': typeof SwiftlyIntelligenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/copilot'
    | '/swiftly/corridors'
    | '/swiftly/deployment'
    | '/swiftly/intelligence'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/copilot'
    | '/swiftly/corridors'
    | '/swiftly/deployment'
    | '/swiftly/intelligence'
  id:
    | '__root__'
    | '/'
    | '/api/copilot'
    | '/swiftly/corridors'
    | '/swiftly/deployment'
    | '/swiftly/intelligence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCopilotRoute: typeof ApiCopilotRoute
  SwiftlyCorridorsRoute: typeof SwiftlyCorridorsRoute
  SwiftlyDeploymentRoute: typeof SwiftlyDeploymentRoute
  SwiftlyIntelligenceRoute: typeof SwiftlyIntelligenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swiftly/intelligence': {
      id: '/swiftly/intelligence'
      path: '/swiftly/intelligence'
      fullPath: '/swiftly/intelligence'
      preLoaderRoute: typeof SwiftlyIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swiftly/deployment': {
      id: '/swiftly/deployment'
      path: '/swiftly/deployment'
      fullPath: '/swiftly/deployment'
      preLoaderRoute: typeof SwiftlyDeploymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swiftly/corridors': {
      id: '/swiftly/corridors'
      path: '/swiftly/corridors'
      fullPath: '/swiftly/corridors'
      preLoaderRoute: typeof SwiftlyCorridorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/copilot': {
      id: '/api/copilot'
      path: '/api/copilot'
      fullPath: '/api/copilot'
      preLoaderRoute: typeof ApiCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCopilotRoute: ApiCopilotRoute,
  SwiftlyCorridorsRoute: SwiftlyCorridorsRoute,
  SwiftlyDeploymentRoute: SwiftlyDeploymentRoute,
  SwiftlyIntelligenceRoute: SwiftlyIntelligenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
